In [102]:
import warnings
warnings.filterwarnings('ignore')

In [103]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [113]:
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Read the CSV and Perform Basic Data Cleaning

In [105]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [106]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

# Split the Data into Training and Testing

In [107]:
# Create our features
#X = df[columns]
#X = df.drop(columns="loan_status")
X = df.drop('loan_status', axis=1)
X = pd.get_dummies(X)

# Create our target
y = df["loan_status"]

In [108]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,issue_d_Mar-2019,pymnt_plan_n,initial_list_status_f,initial_list_status_w,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,application_type_Individual,application_type_Joint App,hardship_flag_N,debt_settlement_flag_N
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,68817.0
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.177238,1.0,0.123879,0.876121,0.383161,0.616839,0.860340,0.139660,1.0,1.0
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.381873,0.0,0.329446,0.329446,0.486161,0.486161,0.346637,0.346637,0.0,0.0
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.0,1.0
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,1.0,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.0,1.0
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,1.0,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.0,1.0
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.0

In [109]:
# Check the balance of our target values
df['loan_status'].value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [110]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=8)
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
Counter(y_train)

Counter({'low_risk': 51343, 'high_risk': 269})

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [119]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE
rf_model = BalancedRandomForestClassifier(n_estimators=100, random_state=1) 
rf_model = rf_model.fit(X_train_scaled,y_train)

print(f'Training Score: {rf_model.score(X_train_scaled, y_train)}')
print(f'Testing Score: {rf_model.score(X_test_scaled, y_test)}')

Training Score: 0.8984344726032706
Testing Score: 0.8935193257773902

In [120]:
# Calculated the balanced accuracy score
y_pred = rf_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.7869906265860023

In [121]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[   53,    25],
       [ 1807, 15320]])

In [122]:
# Print the imbalanced classification report
report = classification_report_imbalanced(y_test, y_pred)
print(report)

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.03      0.68      0.89      0.05      0.78      0.59        78
   low_risk       1.00      0.89      0.68      0.94      0.78      0.62     17127

avg / total       0.99      0.89      0.68      0.94      0.78      0.62     17205

In [123]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
importances = rf_model.feature_importances_
importances
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.07936781186412711, 'total_rec_prncp'),
 (0.06981768798073894, 'total_pymnt_inv'),
 (0.05112458843440454, 'last_pymnt_amnt'),
 (0.050978704885602785, 'total_rec_int'),
 (0.04937181845622267, 'total_pymnt'),
 (0.03319856648919192, 'int_rate'),
 (0.02177550447183606, 'issue_d_Jan-2019'),
 (0.018312804449746495, 'installment'),
 (0.018225937319648788, 'dti'),
 (0.01757994867985834, 'out_prncp_inv'),
 (0.01736143463616971, 'out_prncp'),
 (0.016278065156695685, 'max_bal_bc'),
 (0.0158238950099717, 'il_util'),
 (0.015705096191609605, 'mo_sin_old_il_acct'),
 (0.015248851161499375, 'total_rev_hi_lim'),
 (0.015212021534079679, 'mo_sin_old_rev_tl_op'),
 (0.01493249665468433, 'tot_cur_bal'),
 (0.014925960338724058, 'mths_since_recent_inq'),
 (0.014897300535939396, 'tot_hi_cred_lim'),
 (0.014719382344775288, 'total_bc_limit'),
 (0.014115831459645324, 'total_il_high_credit_limit'),
 (0.014023186528041602, 'annual_inc'),
 (0.013809870236326264, 'revol_bal'),
 (0.01377621606809343, 'total_bal_il'),
 (0.013268471981734024, 'mths_since_recent_bc'),
 (0.0131349036769061, 'loan_amnt'),
 (0.012781316354372858, 'issue_d_Mar-2019'),
 (0.012760228503248525, 'avg_cur_bal'),
 (0.01269985883006012, 'bc_open_to_buy'),
 (0.01192978649700418, 'all_util'),
 (0.011442394623041321, 'total_bal_ex_mort'),
 (0.0110038561195349, 'mths_since_rcnt_il'),
 (0.010994516873766286, 'bc_util'),
 (0.010742094287585442, 'num_rev_accts'),
 (0.010426123068048134, 'num_rev_tl_bal_gt_0'),
 (0.009467663089841928, 'num_actv_rev_tl'),
 (0.009087767397636698, 'num_bc_tl'),
 (0.009060036861372588, 'total_acc'),
 (0.009030000127198462, 'num_sats'),
 (0.008916640528036323, 'inq_last_12m'),
 (0.008770780777834553, 'pct_tl_nvr_dlq'),
 (0.008477771057966295, 'mo_sin_rcnt_tl'),
 (0.008461309966816214, 'num_il_tl'),
 (0.00841864591132601, 'mo_sin_rcnt_rev_tl_op'),
 (0.008321360133972843, 'open_acc'),
 (0.008197826240013641, 'num_op_rev_tl'),
 (0.007858281544662315, 'num_actv_bc_tl'),
 (0.00781261501748448, 'acc_open_past_24mths'),
 (0.007650795886868481, 'num_tl_op_past_12m'),
 (0.007607597351776203, 'inq_fi'),
 (0.007537887435607033, 'total_cu_tl'),
 (0.007533869100249299, 'num_bc_sats'),
 (0.007231997018120596, 'mort_acc'),
 (0.0066640709813733925, 'percent_bc_gt_75'),
 (0.006456811023022638, 'open_rv_24m'),
 (0.0064022167817202515, 'open_il_24m'),
 (0.006089559504458738, 'total_rec_late_fee'),
 (0.005838349199709639, 'issue_d_Feb-2019'),
 (0.005501175373204329, 'open_act_il'),
 (0.005443682305450242, 'inq_last_6mths'),
 (0.005256745679276932, 'open_acc_6m'),
 (0.0051577182586514825, 'next_pymnt_d_Apr-2019'),
 (0.004357853300729398, 'next_pymnt_d_May-2019'),
 (0.004348662940381223, 'delinq_2yrs'),
 (0.004188422737096875, 'open_rv_12m'),
 (0.004052190374494793, 'num_accts_ever_120_pd'),
 (0.0036247996587202196, 'tot_coll_amt'),
 (0.0032458654105774116, 'open_il_12m'),
 (0.002938850067676562, 'verification_status_Not Verified'),
 (0.0025936931683359695, 'verification_status_Verified'),
 (0.0022956615046916583, 'application_type_Individual'),
 (0.0022007515746492057, 'verification_status_Source Verified'),
 (0.0021245128290674404, 'home_ownership_RENT'),
 (0.0018700866887891448, 'pub_rec'),
 (0.0015011228774120576, 'pub_rec_bankruptcies'),
 (0.0014486913967669821, 'application_type_Joint App'),
 (0.0013600650439531277, 'home_ownership_OWN'),
 (0.001073048857325274, 'home_ownership_MORTGAGE'),
 (0.0010274598795317529, 'initial_list_status_f'),
 (0.0007874275734186209, 'initial_list_status_w'),
 (0.0005801510134716729, 'num_tl_90g_dpd_24m'),
 (0.0002351545177795342, 'collections_12_mths_ex_med'),
 (6.41529923419241e-05, 'chargeoff_within_12_mths'),
 (6.166933620257497e-05, 'home_ownership_ANY'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan_n'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag_N'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag_N'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [124]:
# Train the EasyEnsembleClassifier
# YOUR CODE HERE
from imblearn.ensemble import EasyEnsembleClassifier
ab_model = EasyEnsembleClassifier(n_estimators=100, random_state=1) 
ab_model = ab_model.fit(X_train_scaled,y_train)

In [125]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred = ab_model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred)

0.9023370656318632

In [126]:
# Display the confusion matrix
# YOUR CODE HERE
cm=confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm,index=["Actual High_Risk","Actual Low_Risk"],
                     columns=["Predicted High_Risk","Predicted Low_risk"])
display(cm_df)

                  Predicted High_Risk  Predicted Low_risk
Actual High_Risk                   67                  11
Actual Low_Risk                   930               16197

In [127]:
# Print the imbalanced classification report
# YOUR CODE HERE
report = classification_report_imbalanced(y_test, y_pred)
print(report)

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.07      0.86      0.95      0.12      0.90      0.81        78
   low_risk       1.00      0.95      0.86      0.97      0.90      0.82     17127

avg / total       1.00      0.95      0.86      0.97      0.90      0.82     17205

In [128]:
from sklearn.metrics import classification_report
print("classification Report")
print(classification_report(y_test,y_pred))

classification Report
              precision    recall  f1-score   support

   high_risk       0.07      0.86      0.12        78
    low_risk       1.00      0.95      0.97     17127

    accuracy                           0.95     17205
   macro avg       0.53      0.90      0.55     17205
weighted avg       1.00      0.95      0.97     17205